language: node_js
node_js:
  - lts/boron
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kyWNrVZuxvfjbE/aPKsafxas35J6hdGZxysTFdfsxWgCAcfKp3djMSvZ9/g1bOFiOpJknbu+J/EpnAD+dfUFHJdEJg8dfvQevpiwUCkDWKWqP62DR9e8oHQ0a4gBMEQ7qLq8l5V7WZs4WJb+9I7BLDSWzvJkuwTGH1Nr8dJAwy0MQghcpJZTrZ/f+FqRe7sJXPnzRXE8hl6pjcUUDzn2BDltSCRoeW0dGnmJVV0SulslFf9ZeoqglqTlCEn7ejsuoBOQM5QjXCnztfjYefMRXPACNOAimVIdOQq83tqBrNGOPvx5Fxby+mSfrwiJweK54Vthh7FDKs89B7YBfim7gsa7e/hrYj76nj8GAboyh1xiq6fF1ScsmVOVcXmbv1JA8rO1cR/3jze+aiOpTXNBAdqfSyTEwYG7y8+/x0VeVLTg6x4H8hsjOsLV5TWGU3CBbyuG52g9oYbcBxs0gismR1s9Df0QR5VZVOu6JIU+xgRQR68dvmvVku06pxiEKIt/iyZtWGdzy+pEwEt1/sSqsDp26mOH2RHHDvDxRpdEYlfzJUiMSYcoOSnsUbZW737kChu/7esPMW2q++Q6+qBrnAhrL4ZAK0n6HwKmgeXrywCZ8fOnP9shxybGL4EqELVodbtz0+ZAcWCs+2iJ8hFkpdZgWC3U3UwsUpcdl3OqcgQ=
  file:
    - 'link-rel.js'
    - 'link-rel.min.js'
  on:
    tags: true
